/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, double num1, double num2, char operador)
{
	CLIENT *clnt;
	double  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operador)
	{
	case '+':
		result = sumar_1(num1, num2, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	
	case '-':
		result = restar_1(num1, num2, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	case '*':
		result = multiplicar_1(num1, num2, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	case '/':
		result = dividir_1(num1, num2, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	case '^':
		result = potencia_1(num1, num2, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	// case 'v':
	// 	result = raiz_1(num2, num2, clnt);
	// 	if (result == (double *) NULL) {
	// 		clnt_perror (clnt, "call failed");
	// 	}
	// 	break;

	case '!':
		result = factorial_1(num1, clnt);
		if (result == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	default:
		printf("Operacion no valida, por favor introduzca una operacion valida\n");
		break;
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char operador;
	double num1, num2;

	if (argc != 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	do
	{
		printf("¿Que operacion quiere realizar?\n");
		printf(" + : Para realizar una suma\n");
		printf(" - : Para realizar una resta\n");
		printf(" * : Para realizar una multiplicacion\n");
		printf(" / : Para realizar una division\n");
		printf(" ^ : Para realizar una potencia\n");
		// printf(" v : Para realizar una raiz\n");
		printf(" ! : Para realizar un factorial\n");
		printf(" s : Para salir\n");

		scanf(" %c", &operador);

		if(operador == 's')
			break;

		switch (operador)
		{
		case '+': case '-': case '*': case '/':
			printf("Introduzca el primer numero\n");
			scanf("%lf", &num1);
			
			printf("Introduzca el segundo numero\n");
			scanf("%lf", &num2);
			break;
		
		case '^':
			printf("Introduzca la base\n");
			scanf("%lf", &num1);
			
			printf("Introduzca el exponente\n");
			scanf("%lf", &num2);
			break;

		// case 'v':
		// 	printf("Introduzca el indice\n");
		// 	scanf("%lf", &num1);
			
		// 	printf("Introduzca el radicando\n");
		// 	scanf("%lf", &num2);
		// 	break;

		case '!':
			printf("Introduzca el numero\n");
			scanf("%lf", &num1);
			break;
		}
		
		calculadora_1 (host, num1, num2, operador);

		printf("\n ----------------------------------------------- \n\n");

	} while (1);
exit (0);
}
