/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

double *
sumar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1 + arg2);

	printf("La operacion realizada es una suma --> %lf + %lf = %lf\n\n", arg1, arg2, result);

	return &result;
}

double *
restar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1 - arg2);

	printf("La operacion realizada es una resta --> %lf - %lf = %lf\n\n", arg1, arg2, result);

	return &result;
}

double *
multiplicar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1 * arg2);

	printf("La operacion realizada es una multiplicacion --> %lf * %lf = %lf\n\n", arg1, arg2, result);

	return &result;
}

double *
dividir_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1 / arg2);

	printf("La operacion realizada es una division --> %lf / %lf = %lf\n\n", arg1, arg2, result);

	return &result;
}

double *
potencia_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;
	double calculo = 1.0;

	for(int i = 1; i <= arg2; i++)
		calculo = calculo * arg1;

	result = calculo;

	printf("La operacion realizada es una potencia --> %lf ^ %lf = %lf\n\n", arg1, arg2, result);

	return &result;
}

double *
raiz_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = sqrt(arg1);
	printf("La operacion realizada es una potencia --> √ %lf = %lf\n\n", arg1, result);

	return &result;
}

double *
factorial_1_svc(double arg1,  struct svc_req *rqstp)
{
	static double  result;

	double calculo = arg1;

	for(int i = arg1 - 1; i >= 2; i--)
		calculo = calculo * i;

	result = calculo;

	printf("La operacion realizada es un factorial --> %lf! = %lf\n\n", arg1, result);

	return &result;
}
