/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <math.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operacion_result {
	int errno;
	union {
		double result;
	} operacion_result_u;
};
typedef struct operacion_result operacion_result;

struct sumar_1_argument {
	double arg1;
	double arg2;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	double arg1;
	double arg2;
};
typedef struct restar_1_argument restar_1_argument;

struct multiplicar_1_argument {
	double arg1;
	double arg2;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

struct dividir_1_argument {
	double arg1;
	double arg2;
};
typedef struct dividir_1_argument dividir_1_argument;

struct potencia_1_argument {
	double arg1;
	double arg2;
};
typedef struct potencia_1_argument potencia_1_argument;

struct raiz_1_argument {
	double arg1;
	double arg2;
};
typedef struct raiz_1_argument raiz_1_argument;

struct modulo_1_argument {
	double arg1;
	double arg2;
};
typedef struct modulo_1_argument modulo_1_argument;

#define CALCULADORA 0x20000155
#define CALCULADORA_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  operacion_result * sumar_1(double , double , CLIENT *);
extern  operacion_result * sumar_1_svc(double , double , struct svc_req *);
#define restar 2
extern  operacion_result * restar_1(double , double , CLIENT *);
extern  operacion_result * restar_1_svc(double , double , struct svc_req *);
#define multiplicar 3
extern  operacion_result * multiplicar_1(double , double , CLIENT *);
extern  operacion_result * multiplicar_1_svc(double , double , struct svc_req *);
#define dividir 4
extern  operacion_result * dividir_1(double , double , CLIENT *);
extern  operacion_result * dividir_1_svc(double , double , struct svc_req *);
#define potencia 5
extern  operacion_result * potencia_1(double , double , CLIENT *);
extern  operacion_result * potencia_1_svc(double , double , struct svc_req *);
#define raiz 6
extern  operacion_result * raiz_1(double , double , CLIENT *);
extern  operacion_result * raiz_1_svc(double , double , struct svc_req *);
#define factorial 7
extern  operacion_result * factorial_1(double , CLIENT *);
extern  operacion_result * factorial_1_svc(double , struct svc_req *);
#define modulo 8
extern  operacion_result * modulo_1(double , double , CLIENT *);
extern  operacion_result * modulo_1_svc(double , double , struct svc_req *);
#define vAbsoluto 9
extern  operacion_result * vabsoluto_1(double , CLIENT *);
extern  operacion_result * vabsoluto_1_svc(double , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  operacion_result * sumar_1();
extern  operacion_result * sumar_1_svc();
#define restar 2
extern  operacion_result * restar_1();
extern  operacion_result * restar_1_svc();
#define multiplicar 3
extern  operacion_result * multiplicar_1();
extern  operacion_result * multiplicar_1_svc();
#define dividir 4
extern  operacion_result * dividir_1();
extern  operacion_result * dividir_1_svc();
#define potencia 5
extern  operacion_result * potencia_1();
extern  operacion_result * potencia_1_svc();
#define raiz 6
extern  operacion_result * raiz_1();
extern  operacion_result * raiz_1_svc();
#define factorial 7
extern  operacion_result * factorial_1();
extern  operacion_result * factorial_1_svc();
#define modulo 8
extern  operacion_result * modulo_1();
extern  operacion_result * modulo_1_svc();
#define vAbsoluto 9
extern  operacion_result * vabsoluto_1();
extern  operacion_result * vabsoluto_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operacion_result (XDR *, operacion_result*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);
extern  bool_t xdr_potencia_1_argument (XDR *, potencia_1_argument*);
extern  bool_t xdr_raiz_1_argument (XDR *, raiz_1_argument*);
extern  bool_t xdr_modulo_1_argument (XDR *, modulo_1_argument*);

#else /* K&R C */
extern bool_t xdr_operacion_result ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();
extern bool_t xdr_dividir_1_argument ();
extern bool_t xdr_potencia_1_argument ();
extern bool_t xdr_raiz_1_argument ();
extern bool_t xdr_modulo_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
